@startuml
class 读者{
姓名
借书卡号
图书限额
已借图书数
}
class 借阅记录{
借书日期
应还日期
还书日期
}
class 预定记录{
预定日期
}
class 逾期记录{
逾期天数
应缴罚款
}
class 图书管理员{
姓名
工号
}
class 资源项{
馆藏流水号
状态
}

class 馆藏图书品种{
书名
作者
出版社
出版日期
价格
简介
总数量
可借数量
}
读者 - 借阅记录
读者 "1"--"*" 预定记录
借阅记录 "0..1"--"1" 资源项
借阅记录 "1"--"0..1" 逾期记录
借阅记录 "*"--"1" 图书管理员:登记
图书管理员 "1"--"*" 馆藏图书品种:管理
预定记录 "*"--"1" 馆藏图书品种:被预定
资源项 "*"--*"1" 馆藏图书品种:拥有
@enduml