@startuml
object 图书管理员1{
姓名=楚风
工号=123456
}
object 借阅记录2{
借阅人姓名=袁鑫
借书卡号=201710414325
借书日期=2020-01-05
应还日期=2020-02-05
还书日期=2020-02-08
}
object 逾期记录1{
逾期天数=3
应缴罚款=9
}

object 图书品种2{
书名=流浪地球
国际书号=667
作者=刘慈欣
出版社=歌者出版社
....
}
图书管理员1 "1"-"*" 借阅记录2
借阅记录2 -- 逾期记录1
图书管理员1 "1"--"*" 图书品种2
@enduml
