@startuml
object 读者1{
姓名=袁鑫
借书卡号=201710414325
借书限额=10
可用限额=2
}
object 借阅记录1{
借书日期=2020-01-05
应还日期=2020-02-05
还书日期=2020-02-01
}

object 图书1{
馆藏流水号=20200105001
状态=借出
}

object 图书品种1{
书名=三体
国际书号=666
作者=刘慈欣
出版社=歌者出版社
....
}

读者1 "1"-"*" 借阅记录1
借阅记录1 "0..1"--"1" 图书1
图书1 -left- 图书品种1

@enduml
