@startuml
actor 图书管理员

activate 图书管理员
图书管理员 -> 读者:验证读者
activate 读者
读者 -> 图书管理员:返回读者信息

deactivate 读者

图书管理员 -> 资源项:获取资源项
activate 资源项
图书管理员 -> 资源项:借出资源


资源项 -> 馆藏图书品种:查找资源品种
activate 馆藏图书品种
资源项 -> 馆藏图书品种:减少可借数量
馆藏图书品种 -> 图书管理员:返回资源信息
deactivate 馆藏图书品种
deactivate 资源项
图书管理员 -> 读者:更改读者借书限额
activate 读者
deactivate 读者
图书管理员 -> 借阅记录:创建借阅记录
activate 借阅记录
图书管理员 -> 借阅记录:打印借书清单
deactivate 借阅记录
deactivate 图书管理员
@enduml